# Generated by Django 5.0.1 on 2024-03-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredUsers',
            new_name='RegisteredUser',
        ),
    ]
