# Generated by Django 5.0.1 on 2024-03-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappproducts', '0003_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
