# Generated by Django 5.0.1 on 2024-03-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapporders', '0004_productinbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
