# Generated by Django 5.0.1 on 2024-03-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapporders', '0005_productinbasket_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='number',
            new_name='nmb',
        ),
    ]
